<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Shubham" failures="1" tests="2" name="Submit order test" time="12.208" errors="0" timestamp="2025-03-24T02:10:47 IST">
  <testcase classname="mavenPractice.ecommerceUITest" name="createOrder" time="5.289"/>
  <testcase classname="mavenPractice.ecommerceUITest" name="dependencyCode" time="0.92">
    <failure type="java.lang.AssertionError" message="expected [You have No Orders to show at this time. Please Visit Back Us] but found [You have No Orders to show at this time.
Please Visit Back Us]">
      <![CDATA[java.lang.AssertionError: expected [You have No Orders to show at this time. Please Visit Back Us] but found [You have No Orders to show at this time.
Please Visit Back Us]
at mavenPractice.ecommerceUITest.dependencyCode(ecommerceUITest.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- dependencyCode -->
  <testcase classname="mavenPractice.ecommerceUITest" name="validateErrorPopup" time="0.0">
    <ignored/>
  </testcase> <!-- validateErrorPopup -->
</testsuite> <!-- Submit order test -->
